config/routes.rb
Rails.application.routes.draw do
  resources :sharks
  resources :students

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shark.rb
class Shark < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sharks_controller.rb
class SharksController < ApplicationController
  before_action :set_shark, only: %i[ show edit update destroy ]

  # GET /sharks or /sharks.json
  def index
    @sharks = Shark.all
    @shark = Shark.new
  end

  # GET /sharks/1 or /sharks/1.json
  def show
  end

  # GET /sharks/new
  def new
    @shark = Shark.new
  end

  # GET /sharks/1/edit
  def edit

  end

  # POST /sharks or /sharks.json
  def create
    @shark = Shark.new(shark_params)

    respond_to do |format|
      # binding.pry
      if @shark.save
        format.html { redirect_to @shark, notice: "Shark was successfully created." }
        # format.json { render :show, status: :created, location: @shark }
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sharks/1 or /sharks/1.jso
  def update
    respond_to do |format|
      if @shark.update(shark_params)
        format.html { redirect_to @shark, notice: "Shark was successfully updated." }
        format.json { render :show, status: :ok, location: @shark }
        format.js
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sharks/1 or /sharks/1.json
  def destroy
    @shark.destroy
    respond_to do |format|
      format.html { redirect_to sharks_url, notice: "Shark was successfully destroyed." }
      format.json { head :no_content }
      format.js    
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shark
      @shark = Shark.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shark_params
      params.require(:shark).permit(:name, :facts)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def index
    @students = Student.all
    @student = Student.new
	end
	def new
    @student = Student.new
	end
	def create
	  @student = Student.new(student_params)
	  respond_to do |format|
	  	if @student.save
	  	   format.html { redirect_to @student, notice: "student was successfully created." }
	  	   format.js
	  	else
	  		format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @student.errors, status: :unprocessable_entity }
        end
      end
    end
    def update

    	respond_to do|format|
    		# binding.pry
    		set_student
    	  if @student.update(student_params)
    	  	# binding.pry
    	  	# set_studentSS
    	  	format.html { redirect_to @student, notice: "Student was successfully updated." }
        	format.json { render :show, status: :ok, location: @student }
        	format.js
          else
        	format.html { render :edit, status: :unprocessable_entity }
        	format.json { render json: @student.errors, status: :unprocessable_entity }
          end
        end
    end
    def destroy
    	# binding.pry
    	set_student
    	@student.destroy
    	respond_to do|format|
    		format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      		format.json { head :no_content }
      		format.js 
      	end
    end
    def show
    	set_student
    end
    def edit
    	set_student
      
    end

	private
	  def set_student
      	@student = Student.find(params[:id])
      end 
      def student_params
        params.require(:student).permit(:name, :f_name)
      end
end
	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sharks_helper.rb
module SharksHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ajaxapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sharks/_form.html.erb
<% if shark&.id.present? %>
  <%# binding.pry %>
  <%= form_for( @shark, remote: true) do |form| %>

    <% if shark.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(shark.errors.count, "error") %> prohibited this shark from being saved:</h2>

        <ul>
          <% shark.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name ,id: "name_field"%>
    </div>

    <div class="field">
      <%= form.label :facts %>
      <%= form.text_area :facts ,id: "fact_field" %>
    </div>

    <div class="actions">
      <%= form.submit %>

    </div>
  <% end %>
<% else %>
  <%= form_for( :shark, remote: true) do |form| %>

    <% if shark.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(shark.errors.count, "error") %> prohibited this shark from being saved:</h2>

        <ul>
          <% shark.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name ,id: "name_field"%>
    </div>

    <div class="field">
      <%= form.label :facts %>
      <%= form.text_area :facts ,id: "fact_field" %>
    </div>

    <div class="action">
      <%= form.submit class: "btn btn-primary btn-sm"  %>


    </div>
  <% end %>
<% end %>

app/views/sharks/_tables.html.erb
<%#binding.pry %>
 <tr class="yasir-<%= shark.id %> ">
    <td><%= shark.id %></td>
    <td><%= shark.name %></td>
    <td><%= shark.facts %></td>
    <td><%= link_to 'Show', shark %></td>
    <td><%= link_to 'Edit', edit_shark_path(shark), remote: :true %></td>
    <td><%= link_to 'Destroy', shark, method: :delete, remote: :true%></td>
  </tr>

app/views/sharks/_update_row.html.erb
<td><%= shark.id %></td>
    <td><%= shark.name %></td>
    <td><%= shark.facts %></td>
    <td><%= link_to 'Show', shark %></td>
    <td><%= link_to 'Edit', edit_shark_path(shark), remote: :true %></td>
    <td><%= link_to 'Destroy', shark, method: :delete, remote: :true%></td>

app/views/sharks/create.js.erb
$('#tbl_id').append('<%= j(render(partial: "sharks/tables", locals: { shark: @shark }))%>')
$('#name_field').val("")
$('#fact_field').val("")

app/views/sharks/destroy.js.erb
// $('.yasir-<%=params[:id].to_i %>').remove()

$('.yasir-<%=params[:id] %>').remove()

app/views/sharks/edit.html.erb
<h1>Editing Shark</h1>

<%= render 'form', shark: @shark %>

<%= link_to 'Show', @shark %> |
<%= link_to 'Back', sharks_path %>

app/views/sharks/edit.js.erb
$('#form-edit').html('<%= j(render(partial: "sharks/form", locals: { shark: @shark}))%>')
$('#name_field').val("<%= @shark.name %>")
$('#fact_field').val("<%= @shark.facts %>")

app/views/sharks/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Sharks</h1>
<div id="form-edit">
  <%= render 'form', shark: @shark %>
</div>
<table class="table">
    <thead class="thead-dark">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Fact</th>
        <th>show</th>
        <th>edit</th>
        <th>destroy</th>
      </tr>
    </thead>
  <tbody id="tbl_id">
    <%# binding.pry %>
    <% @sharks.each do |shark| %>
      <%= render 'tables', shark: shark %>
     
    <% end %>
  </tbody>
</table>
<%= link_to 'New Shark', new_shark_path %>

app/views/sharks/new.html.erb
<h1>New Shark</h1>

<%= render 'form', shark: @shark %>

<%= link_to 'Back', sharks_path %>

app/views/sharks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shark.name %>
</p>

<p>
  <strong>Facts:</strong>
  <%= @shark.facts %>
</p>

<%= link_to 'Edit', edit_shark_path(@shark) %> |
<%= link_to 'Back', sharks_path %>

app/views/sharks/update.js.erb
<%# binding.pry %>
$('.yasir-<%=@shark.id %>').html('<%= j(render(partial: "sharks/update_row", locals: { shark: @shark }))%>')
$('#name_field').val("")
$('#fact_field').val("")

app/views/students/_form.html.erb
<% if @student&.id.present? %>
  <%= form_for( @student, remote: true ) do |form| %>

	<div class="field">
      <%= form.label :name %>
      <%= form.text_field :name ,id: "name_field"%>
    </div>

    <div class="field">
      <%= form.label :f_name %>
      <%= form.text_area :f_name ,id: "fname_field" %>
    </div>

    <div class="action">
      <%= form.submit class: "btn btn-primary btn-sm" %>



    </div>
  <% end %>
  <%else %>
    <%= form_for( :student, remote: true ) do |form| %>
   < <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name ,id: "name_field"%>
    </div>

    <div class="field">
      <%= form.label :f_name %>
      <%= form.text_area :f_name ,id: "fname_field" %>
    </div>

    <div class="action">
      <%= form.submit class: "btn btn-primary btn-sm" %>



    </div> 
  <% end %>
<% end %>

app/views/students/_tablesqqq.html.erb
<tr class="iqbal<%= student.id %>">
    <td><%= student.id %></td>
    <td><%= student.name %></td>
    <td><%= student.f_name %></td>
    <td><%= link_to 'Show', student %></td>
    <td><%= link_to 'Edit', edit_student_path(student), remote: :true %></td>
    <td><%= link_to 'Destroy', student, method: :delete, remote: :true %></td>
  </tr>
  <!-- class="yasir-<%#= student.id %> " -->

app/views/students/_update_row.html.erb
<td><%= student.id %></td>
    <td><%= student.name %></td>
    <td><%= student.f_name %></td>
    <td><%= link_to 'Show', student %></td>
    <td><%= link_to 'Edit', edit_student_path(student), remote: :true %></td>
    <td><%= link_to 'Destroy', student, method: :delete, remote: :true %></td>
  </tr>

app/views/students/create.js.erb
$('#create_id').append('<%= j(render(partial: "students/tablesqqq", locals: { student: @student }))%>')
$('#name_field').val("")
$('#fname_field').val("")

app/views/students/destroy.js.erb
$('.iqbal<%= params[:id] %>').remove()

app/views/students/edit.html.erb
<h1>Editing Student</h1>
<%= render 'form', student: @student %>
<%= link_to 'Show', @student %> ||
<%= link_to 'Back', students_path %>

app/views/students/edit.js.erb
$('#form_edit').html('<%= j(render(partial: "students/form", locals: { student: @student}))%>')
$('#name_field').val("<%= @student.name %>")
$('#fname_field').val("<%= @student.f_name %>")

app/views/students/index.html.erb
<h1>student</h1>
<div id=form_edit>

<%= render 'form', student: @student %><br>
</div>

<table class="table">
    <thead class="thead-dark">
      <tr>
        <th>ID</th>
        <th>s name</th>
        <th>Fname</th>
        <th>show</th>
        <th>edit</th>
        <th>destroy</th>
      </tr>
    </thead>
  <tbody id="create_id">
  	<%# binding.pry %>
  	  <% @students.each do |student| %>

      <%= render 'tablesqqq', student: student %>
     
      <% end %>
  <!-- </tbody> -->
</table>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p><br><br>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>f name:</strong>
  <%= @student.f_name %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/students/update.js.erb
$('.iqbal<%=@student.id %>').html('<%= j(render(partial: "students/update_row", locals: { student: @student })) %>')
$('#name_field').val("")
$('#fname_field').val("")